### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by Offliner33** [t123yh/ipxrouter#1]
As the title states. I have no idea how to compile the client part. I would love to use this myself.

**Comment by t123yh** [comment]
You may fork this repo and setup GitHub Actions. CI will compile it for you. Alternatively, you can use Visual Studio to compile it.

**Comment by Offliner33** [comment]
I have forked the repo. I am new to CI in general so I don't know if I've done it correctly or how to trigger it. Sorry if this seems dumb and thanks for the quick response.

**Comment by Offliner33** [comment]
I figured it out. Thanks for your help!
